version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
      - build

jobs:
  runner:
    machine: true
    resource_class: fy9havcxxh2v26vozdiaju/res
    steps:
      - run: 
          name: Greetings
          command: echo "Hi I'm on Runners! sajjdsk"

  build:
    machine: true
    resource_class: fy9havcxxh2v26vozdiaju/res
    steps:
      - run:
          name: Install Deps
          command: sudo port install pkgconfig freetype libjpeg-turbo libheif libpng tiff libtool openexr openjpeg webp libraw ghostscript

        
