name: Appimage (New)
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            name: Build AppImage
            arch: aarch64
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create builder user
        run: |
          pacman -Sy --noconfirm shadow sudo base-devel
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -Rv builder:builder $GITHUB_WORKSPACE

      - name: Run as builder
        run: |
          su - builder
          pwd
          ls
          whoami

      - name: Get dependencies
        run: |
          su - builder
          pwd
          ls
          whoami
          cd appimage
          chmod +x ./get-dependencies.sh && ./get-dependencies.sh

      - name: Build Converseen
        run: |
          su - builder
          cd appimage/build
          makepkg -si --noconfirm

      - name: Make AppImage
        run: |
          su - builder
          cd appimage
          chmod +x ./*-appimage.sh && ./*-appimage.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage-${{ matrix.arch }}
          path: appimage/dist
