name: Appimage (New)
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.name }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: Build AppImage
            arch: x86_64
          - runs-on: ubuntu-24.04-arm
            name: Build AppImage
            arch: aarch64
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Setup Container
        run: |
          pacman -Sy base-devel sudo
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          su - builder

      - name: Install Custom ImageMagick
      - run: |
          pwd
          ls
          whoami
          wget https://mirror.dogado.de/imagemagick/ImageMagick.tar.bz2
          tar -xvf ImageMagick.tar.bz2
          cd ImageMagick-*/
          ./configure --enable-shared --disable-installed --enable-hdri --without-perl --disable-dependency-tracking --with-gslib=yes --with-openjp2 --with-wmf --without-gvc --with-djvu --without-dps --without-fpx --with-heic=yes --with-rsvg --with-uhdr --with-fftw --with-lqr --without-autotrace --without-dps --without-fpx --without-gcc-arch --with-dejavu-font-dir=/usr/share/fonts/TTF --with-gs-font-dir=/usr/share/fonts/gsfonts --prefix=/usr --sysconfdir=/etc
          
          make -j$(nproc)
          make install

      - name: Get dependencies
        run: chmod +x ./get-dependencies.sh && ./get-dependencies.sh

      - name: Make AppImage
        run: chmod +x ./*-appimage.sh && ./*-appimage.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: AppImage-${{ matrix.arch }}
          path: dist
