# Test build process on various OS and Configurations
name: Windows Test Build
on:
  workflow_dispatch:

env:
  APPIMAGE_DIR: "package/AppImage"
  IM_REPO: "https://github.com/ImageMagick/ImageMagick/releases/download/"
  QT_QPA_PLATFORM: offscreen

jobs:
  build-windows:
    name: Converseen Windows Build
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - qt_version: '5.15.2'
            qt_arch: 'win32_msvc2019'
            imagemagick_arch: 'x86'
            vs_host_arch: 'x86'
            vs_arch: 'x86'
            bits: '32bit'
            cmake_extra_flags: ''
          - qt_version: '6.11.1'
            qt_arch: 'win64_msvc2022_64'
            imagemagick_arch: 'x64'
            vs_host_arch: 'x64'
            vs_arch: 'x64'
            bits: '64bit'
            cmake_extra_flags: '-DUSE_QT6=yes'
          - qt_version: '6.11.1'
            qt_arch: 'win64_msvc2022_arm64_cross_compiled'
            imagemagick_arch: 'arm64'
            vs_host_arch: 'x64'
            vs_arch: 'arm64'
            bits: 'arm64'
            cmake_extra_flags: '-DUSE_QT6=yes'
    
    steps:
      - name: Download ImageMagick for Windows (${{ matrix.bits }})
        shell: powershell
        run: |
            # Get latest version number from GitHub
            $gitTags = git ls-remote --sort="version:refname" --tags https://github.com/ImageMagick/ImageMagick.git
            $lastTagLine = $gitTags[-1]
            $lastTagVersion = $lastTagLine -replace '.*?(\d+\.\d+\.\d+-\d+).*', '$1'
            $latestVersionNumber = $lastTagVersion
            
            Write-Host "Latest ImageMagick Version Found: $latestVersionNumber"
  
            $downloadUrl = "$($env:IM_REPO)$latestVersionNumber/ImageMagick-$latestVersionNumber-Q16-HDRI-${{ matrix.imagemagick_arch }}-dll.exe"
            Write-Host "Downloading from: $downloadUrl"
  
            # Download ImageMagick for Windows
            Invoke-WebRequest -Uri $downloadUrl -OutFile ImageMagick-Installer.exe
      
      - name: Install ImageMagick for Windows (${{ matrix.bits }})
        shell: cmd
        run: |
          ImageMagick-Installer.exe /MERGETASKS=install_devel /VERYSILENT /DIR=ImageMagick
    
      - name: Checkout Converseen
        uses: actions/checkout@v4
        with:
          path: Converseen
          repository: Faster3ck/Converseen
          # ref: dev
      
      - name: Install Qt ${{ matrix.qt_version }} (${{ matrix.bits }})
        uses: jurplel/install-qt-action@v4
        with:
          version: '${{ matrix.qt_version }}'
          host: 'windows'
          target: 'desktop'
          arch: '${{ matrix.qt_arch }}'
          install-deps: 'true'
          set-env: 'true'
          aqtsource: 'git+https://github.com/miurahr/aqtinstall.git@refs/pull/1000/head' # For Qt 6.11.* support (not included in the latest release yet)
      
      - name: Build Converseen (Qt ${{ matrix.qt_version }} ${{ matrix.bits }})
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=${{ matrix.vs_host_arch }} -arch=${{ matrix.vs_arch }}
          
          cd Converseen
          mkdir build
          cd build
      
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DImageMagick_EXECUTABLE_DIR="${{ github.workspace }}\ImageMagick" ${{ matrix.cmake_extra_flags }} ..
          nmake
          cpack -B package
      
      - name: Prepare Artifacts (Qt ${{ matrix.qt_version }} ${{ matrix.bits }})
        shell: cmd
        run: |
          ls
          ls Converseen/build/package/
        
          mkdir artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}
          cp Converseen/build/package/*.msi artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}/
          cp Converseen/build/package/*.zip artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}/
          ls artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}

      - name: Windows Test Run
        shell: powershell
        run: |
          cd Converseen/build/package
          
          Expand-Archive -Path "Converseen.zip" -DestinationPath "."
          cd Converseen
          
          .\converseen.exe -p
      
      - uses: actions/upload-artifact@v7
        with:
          name: Windows-Qt${{ matrix.qt_version }}-${{ matrix.bits }}
          path: 'artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}'
