# Test build process on various OS and Configurations
name: Build
on:
  workflow_dispatch:
jobs:
  build-windows:
    name: Converseen Windows Build
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - qt_version: '5.15.2'
            qt_arch: 'win32_msvc2019'
            imagemagick_arch: 'x86'
            vs_arch: 'x86'
            bits: '32bit'
          - qt_version: '6.9.0'
            qt_arch: 'win64_msvc2022_64'
            imagemagick_arch: 'x64'
            vs_arch: 'x64'
            bits: '64bit'
    
    steps:
      - name: Download ImageMagick for Windows (${{ matrix.bits }})
        shell: powershell
        run: |
          # Get latest version number from GitHub
          $gitTags = git ls-remote --sort="version:refname" --tags https://github.com/ImageMagick/ImageMagick.git
          $lastTagLine = $gitTags[-1]
          $lastTagVersion = $lastTagLine -replace '.*refs/tags/(.*)', '$1'
          $latestVersionNumber = $lastTagVersion
          
          Write-Host "Latest ImageMagick Version Found: $latestVersionNumber"
          
          Invoke-WebRequest -Uri "https://imagemagick.org/archive/binaries/ImageMagick-$latestVersionNumber-Q16-HDRI-${{ matrix.imagemagick_arch }}-dll.exe" -OutFile ImageMagick-Installer.exe
      
      - name: Install ImageMagick for Windows (${{ matrix.bits }})
        shell: cmd
        run: |
          ImageMagick-Installer.exe /MERGETASKS=install_devel /VERYSILENT /DIR=ImageMagick
    
      - name: Checkout Converseen
        uses: actions/checkout@v4
        with:
          path: Converseen
      
      - name: Install Qt ${{ matrix.qt_version }} (${{ matrix.bits }})
        uses: jurplel/install-qt-action@v3
        with:
          version: '${{ matrix.qt_version }}'
          host: 'windows'
          target: 'desktop'
          arch: '${{ matrix.qt_arch }}'
          install-deps: 'true'
          set-env: 'true'
      
      - name: Build Converseen (Qt ${{ matrix.qt_version }} ${{ matrix.bits }})
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.vs_arch }}
          
          cd Converseen
          mkdir build
          cd build
      
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE:STRING=Release -DImageMagick_EXECUTABLE_DIR="${{ github.workspace }}\ImageMagick" ..
          nmake
          cpack -B package
      
      - name: Prepare Artifacts (Qt ${{ matrix.qt_version }} ${{ matrix.bits }})
        shell: cmd
        run: |
          ls
          ls Converseen/build/package/
        
          mkdir artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}
          cp Converseen/build/package/*.msi artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}/
          cp Converseen/build/package/*.zip artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}/
          ls artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-Qt${{ matrix.qt_version }}-${{ matrix.bits }}
          path: 'artifacts-qt${{ matrix.qt_version }}-${{ matrix.bits }}'
