name: Ghostscript

on:
  workflow_dispatch:
  
jobs:
  build-macos:
    name: Ghostscript test
    runs-on: macos-14

    env:
      BASE_DIR: ${{ github.workspace }}/im_build 
      WORKING_DIR: ${{ github.workspace }}

    steps:
    - name: Install dependencies
      run: |
        set -e
        
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install ghostscript tree

    - name: Copy Resources
      run: |
        gs_ver=$(echo $(ls /opt/homebrew/Cellar/ghostscript/) | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')_1

        tree /opt/homebrew/Cellar/ghostscript/
        ls /opt/homebrew/Cellar/ghostscript/$gs_ver/share/ghostscript

        mkdir testres
        cp -RPv /opt/homebrew/Cellar/ghostscript/$gs_ver/share/ghostscript testres

        cd testres/Contents/Resources/ghostscript
        ls

        gs_ver_t=$(echo $(ls) | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
        mv $gs_ver_t gs

        ls
        
        
