name: Converseen macOS Test

on:
  push:
    tags:        
      - '**'
  workflow_dispatch:

jobs:
  build-macos:
    name: Converseen macOS Build
    runs-on: macos-12

    env:
      BASE_DIR: ${{ github.workspace }}/im_build 
      WORKING_DIR: ${{ github.workspace }}

    steps:
    - name: Install dependencies
      run: |
        set -e
        
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install pkg-config freetype jpeg-turbo libheif libpng libtiff libtool openexr openexr openjpeg webp libraw ghostscript aqt

    - name: Install Qt
      shell: bash
      run: |
        aqt install-qt mac desktop 6.7.0 clang_64
      
        #curl -LO https://download.qt.io/official_releases/online_installers/qt-unified-mac-x64-online.dmg

        #chmod a+x qt-unified-mac-x64-online.dmg
        
        #./qt-unified-mac-x64-online.dmg \
        #  --accept-licenses \
        #  --default-answer \
        #  --confirm-command install \
        #  qt.qt6.670.clang_64

    - name: Checkout Converseen
      uses: actions/checkout@v4
      with:
        repository: Faster3ck/Converseen
        path: Converseen

    - name: Set Environment
      id: set-env
      run: |
        file_content=$(tr -d '\r' <converseen/package/macOS/version.txt)

        VERSION=$(echo "$file_content" | grep -oE '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
        BUILD=$(echo "$file_content" | grep -oE '[0-9]+$')

        export LIB_DIR="${BASE_DIR}/lib"
        export LOCAL_LIB="/usr/local/lib"

        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "BUILD=$BUILD" >> $GITHUB_ENV
        echo "LIB_DIR=$LIB_DIR" >> $GITHUB_ENV
        echo "LOCAL_LIB=$LOCAL_LIB" >> $GITHUB_ENV

        echo "ver=$VERSION" >> "$GITHUB_OUTPUT"

        echo "Version: $VERSION"
        echo "Build Number: $BUILD"

    - name: Checkout ImageMagick
      uses: actions/checkout@v4
      with:
        path: ImageMagick
        repository: ImageMagick/ImageMagick
        
    - name: Build ImageMagick
      run: |      
        cd ImageMagick
        ./configure --prefix=${{ github.workspace }}/im_build \
                              --with-quantum-depth=16 \
                              --disable-dependency-tracking \
                              --without-perl \
                              --without-x \
                              --disable-static \
                              --disable-installed \
                              --enable-shared \
                              --with-flif=yes \
                              --with-gslib=yes

        make
        make install
      
    - name: Build Converseen
      run: |
        mkdir build
        cd build

        qmake ../converseen/converseen.pro -spec macx-clang QMAKE_MACOSX_DEPLOYMENT_TARGET=12.0 IM_INSTALL_PREFIX=${{ github.workspace }}/im_build
        make
