name: Multi-Arch Snap

on:
  workflow_dispatch:

env:
  APPIMAGE_DIR: "package/AppImage"
  IM_REPO: "https://github.com/ImageMagick/ImageMagick/releases/download/"
  QT_QPA_PLATFORM: offscreen

jobs:
  snap-build:
    name: Converseen Snap Build (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: amd64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm

    steps:
    - name: Checkout Converseen
      uses: actions/checkout@v4
      with:
        repository: Faster3ck/Converseen

    - name: Build Snap
      uses: snapcore/action-build@v1
      id: snapcraft
      with:
        path: package/Snap
    
    - name: Snap Test Run
      run: |
        sudo snap install --dangerous ${{ steps.snapcraft.outputs.snap }}
        converseen -p
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: snap-${{ matrix.arch }}
        path: ${{ steps.snapcraft.outputs.snap }}
        
