name: My Webhook Triggered Action

on:
  repository_dispatch:
    types: [signature-response]

jobs:
  my-job:
    runs-on: windows-latest
    steps:
      - name: Install Cmdlets
        shell: powershell
        run: Install-Module -Name SignPath -Scope CurrentUser -Force

      - name: Download Signed Artifact
        shell: powershell
        run: |
          $ORGANIZATION_ID="${{ github.event.client_payload.OrganizationId }}"
          $signingRequestID="${{ github.event.client_payload.SigningRequestId }}"
          $SP_API_TOKEN="${{ secrets.SP_API_TOKEN }}"

          Get-SignedArtifact `
          -OrganizationId $ORGANIZATION_ID -ApiToken $SP_API_TOKEN `
          -SigningRequestId $signingRequestID `
          -OutputArtifactPath artifact.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.zip
          
